name: couldai_user_app
description: "crie um app de desenho chamado Drawsk, nesse app será possível aprender a desenhar com aulas, aprender a desenhar qualquer imagem selecionada com um video gerado por IA e compartilhar e vender su..."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
